version: '3.8'

services:
  backend:
    container_name: creator-monk-dev
    build: .
    ports:
      - "8001:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - DEBUG=${DEBUG}
    volumes:
      - .:/app
    restart: unless-stopped